version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: crypto_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - crypto_network

volumes:
  mysql_data:

networks:
  crypto_network:
    driver: bridge
